ARG UBUNTU_TAG=24.04
FROM ubuntu:$UBUNTU_TAG

LABEL maintainer="Mauricio Villegas <mauricio_ville@yahoo.com>"

ENV DEBIAN_FRONTEND=noninteractive

# Install all language packages
RUN apt-get update --fix-missing \
 && apt-get install -y --no-install-recommends \
      rsync \
      tesseract-ocr-* \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

 CMD ["rsync", "-av", "/usr/share/tesseract-ocr/5/tessdata", "/opt/tesseract-ocr"]
