#!/bin/bash

### Create pre-commit symlink if unset ###
GITDIR="";
if [ -d .git ]; then
  GITDIR=".git";
elif [ -f .git ]; then
  GITDIR=$(sed -n '/^gitdir:/{ s|.*: ||; p; }' .git);
fi
if [ ! -d "$GITDIR" ]; then
  echo "${0##*/}: error: unable to find git directory" 1>&2;
  exit 1;
fi
if [ ! -h "$GITDIR/hooks/pre-commit" ]; then
  if [ $(realpath --help 2>&1 | grep -c relative) != 0 ]; then
    HOOK=$(realpath --relative-to="$GITDIR/hooks" ./githook-pre-commit);
  else
    HOOK=$(readlink -f ./githook-pre-commit);
  fi
  ln -fs "$HOOK" "$GITDIR/hooks/pre-commit";
  echo "${0##*/}: creating git pre-commit hook symlink" 1>&2;
  exit 1;
fi


### Update versions on files ###
FILES=( $(git status --porcelain | sed 's| .* | |' | grep '^[MRA]') );
V=$(date -u +%Y.%m.%d);

check_change_after_staged () {
  [ "${2:1:1}" = "M" ] &&
    echo "${0##*/}: error: unable to update version due to change after staged: $1" 1>&2 &&
    exit 1;
}

update_file_version () {
  echo "${0##*/}: updating version of $1" 1>&2;
  sed -r -i 's|([$"])Version:[^$"]*([$"])|\1Version: '"$V"'\2|' "$1";
  git add "$1";
}

n=1;
while [ "$n" -lt "${#FILES[@]}" ]; do
  case "${FILES[$n]}" in
    tesseract-recognize.cc | *.py )
      check_change_after_staged "${FILES[$n]}" "${FILES[$((n+1))]}";
      update_file_version "${FILES[$n]}";
      ;;
  esac
  if [ "${FILES[$n]:$((${#FILES[$n]}-3))}" = ".py" ]; then
    echo "${0##*/}: pylint ${FILES[$n]}" 1>&2;
    pylint --errors-only "${FILES[$n]}";
  fi
  [ "$?" != "0" ] && exit 1;
  n=$((n+2));
done

exit 0;
